// Code generated by blevebindings generator. DO NOT EDIT.

package index

import (
	bleve "github.com/blevesearch/bleve"
	"github.com/stackrox/rox/generated/aux"
	storage "github.com/stackrox/rox/generated/storage"
	search "github.com/stackrox/rox/pkg/search"
	blevesearch "github.com/stackrox/rox/pkg/search/blevesearch"
)

type Indexer interface {
	AddK8SRoleBinding(k8srolebinding *storage.K8SRoleBinding) error
	AddK8SRoleBindings(k8srolebindings []*storage.K8SRoleBinding) error
	Count(q *aux.Query, opts ...blevesearch.SearchOption) (int, error)
	DeleteK8SRoleBinding(id string) error
	DeleteK8SRoleBindings(ids []string) error
	MarkInitialIndexingComplete() error
	NeedsInitialIndexing() (bool, error)
	Search(q *aux.Query, opts ...blevesearch.SearchOption) ([]search.Result, error)
}

func New(index bleve.Index) Indexer {
	return &indexerImpl{index: index}
}
