// Code generated by pg-bindings generator. DO NOT EDIT.

//go:build sql_integration

package postgres

import (
	"context"
	"testing"

	"github.com/jackc/pgx/v4/pgxpool"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/features"
	"github.com/stackrox/rox/pkg/postgres/pgtest"
	"github.com/stackrox/rox/pkg/sac"
	"github.com/stackrox/rox/pkg/testutils"
	"github.com/stackrox/rox/pkg/testutils/envisolator"
	"github.com/stretchr/testify/suite"
)

type InstallationInfosStoreSuite struct {
	suite.Suite
	envIsolator *envisolator.EnvIsolator
	store       Store
	pool        *pgxpool.Pool
}

func TestInstallationInfosStore(t *testing.T) {
	suite.Run(t, new(InstallationInfosStoreSuite))
}

func (s *InstallationInfosStoreSuite) SetupTest() {
	s.envIsolator = envisolator.NewEnvIsolator(s.T())
	s.envIsolator.Setenv(features.PostgresDatastore.EnvVar(), "true")

	if !features.PostgresDatastore.Enabled() {
		s.T().Skip("Skip postgres store tests")
		s.T().SkipNow()
	}

	ctx := sac.WithAllAccess(context.Background())

	source := pgtest.GetConnectionString(s.T())
	config, err := pgxpool.ParseConfig(source)
	s.Require().NoError(err)
	pool, err := pgxpool.ConnectConfig(ctx, config)
	s.Require().NoError(err)

	Destroy(ctx, pool)

	s.pool = pool
	s.store = New(ctx, pool)
}

func (s *InstallationInfosStoreSuite) TearDownTest() {
	if s.pool != nil {
		s.pool.Close()
	}
	s.envIsolator.RestoreAll()
}

func (s *InstallationInfosStoreSuite) TestStore() {
	ctx := sac.WithAllAccess(context.Background())

	store := s.store

	installationInfo := &storage.InstallationInfo{}
	s.NoError(testutils.FullInit(installationInfo, testutils.SimpleInitializer(), testutils.JSONFieldsFilter))

	foundInstallationInfo, exists, err := store.Get(ctx, installationInfo.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundInstallationInfo)

	withNoAccessCtx := sac.WithNoAccess(ctx)

	s.NoError(store.Upsert(ctx, installationInfo))
	foundInstallationInfo, exists, err = store.Get(ctx, installationInfo.GetId())
	s.NoError(err)
	s.True(exists)
	s.Equal(installationInfo, foundInstallationInfo)

	installationInfoCount, err := store.Count(ctx)
	s.NoError(err)
	s.Equal(1, installationInfoCount)
	installationInfoCount, err = store.Count(withNoAccessCtx)
	s.NoError(err)
	s.Zero(installationInfoCount)

	installationInfoExists, err := store.Exists(ctx, installationInfo.GetId())
	s.NoError(err)
	s.True(installationInfoExists)
	s.NoError(store.Upsert(ctx, installationInfo))
	s.ErrorIs(store.Upsert(withNoAccessCtx, installationInfo), sac.ErrResourceAccessDenied)

	foundInstallationInfo, exists, err = store.Get(ctx, installationInfo.GetId())
	s.NoError(err)
	s.True(exists)
	s.Equal(installationInfo, foundInstallationInfo)

	s.NoError(store.Delete(ctx, installationInfo.GetId()))
	foundInstallationInfo, exists, err = store.Get(ctx, installationInfo.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundInstallationInfo)
	s.ErrorIs(store.Delete(withNoAccessCtx, installationInfo.GetId()), sac.ErrResourceAccessDenied)

	var installationInfos []*storage.InstallationInfo
	for i := 0; i < 200; i++ {
		installationInfo := &storage.InstallationInfo{}
		s.NoError(testutils.FullInit(installationInfo, testutils.UniqueInitializer(), testutils.JSONFieldsFilter))
		installationInfos = append(installationInfos, installationInfo)
	}

	s.NoError(store.UpsertMany(ctx, installationInfos))
	allInstallationInfo, err := store.GetAll(ctx)
	s.NoError(err)
	s.ElementsMatch(installationInfos, allInstallationInfo)

	installationInfoCount, err = store.Count(ctx)
	s.NoError(err)
	s.Equal(200, installationInfoCount)
}
